ibabygroup:
  swagger:
    enabled: false
  net:
    host: http://apitest.ibabygroup.cn/
  rest:
    host: http://10.164.12.73:8080/
    token: 2RRO7i13GqNryj3a
  appconfig:
    ignore-auth: true
  duiba:
    appKey: 3YQhqRLMbVJGgtU4fBZuaWBrd38p
    appSecret: 3KnKW8pHFj9BVgpNVfSmGkYBmLbc
spring:
  datasource:
    url: jdbc:mysql://10.164.12.73:3306/member?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: ibaby#2016!QAZ
    type: com.zaxxer.hikari.HikariDataSource
# nginx
app-uac-server-rc:
 ribbon:
  listOfServers: 10.174.231.140:9696